language: node_js

node_js: 10.16.0

install:
  - yarn

script:
  - yarn lint
  - yarn lint:types
  - yarn lint:prettier
  - yarn test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - yarn release

cache:
  yarn: true
  directories:
    - node_modules
